set -g prefix C-x
bind C-x send-prefix

# the time to wait next key when ESC is prefix of some keybindings
set-option -sg escape-time 0

# scrollback
set -g history-limit 100000

# enable focus event which is allow some programs to do some actions when the pane was focused
set-option -g focus-events on

# Enable OSC 52 clipboard copy
set -s set-clipboard on

# set TERM variable
set-option -g default-terminal "tmux-256color" # 基本的にはscreen-256colorかtmux-256colorを設定

# enable Ctrl-Tab
set -g extended-keys always
%if #{>=:#{version},3.5}
set -g extended-keys-format csi-u
%endif

# add support for mouse
set-option -g mouse on
bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind-key -n WheelDownPane select-pane -t= \; send-keys -M

# set vi keybind for copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v     send-keys -X begin-selection
bind-key -T copy-mode-vi C-v   send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y     send-keys -X copy-selection-and-cancel

# Translation
bind-key -T copy-mode-vi t send-keys -X copy-pipe-and-cancel \
    "tr '\n' ' ' | sed 's/[[:space:]]\+/ /g' >/tmp/tmux-trans-#{client_pid}; tmux popup -w 80% -h 60% 'trans :ja -b < /tmp/tmux-trans-#{client_pid}; rm -f /tmp/tmux-trans-#{client_pid}; read'"

# In ssh session
if-shell 'test -n "$SSH_CLIENT"' {
    set -g prefix C-b
    set -g status off
    bind C-b send-prefix
}

# keybindings
bind x kill-pane
bind B new-window -c '#{pane_current_path}'
bind b new-window
bind c split-window -h -c '#{pane_current_path}'
bind C split-window -h
bind v split-window -c '#{pane_current_path}'
bind V split-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind a display-panes
bind t popup -w90% -h90%

# pane border color
set -g pane-border-style fg=colour242
set -g pane-active-border-style fg=colour255

# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g mode-style "bg=#303030"

# Status line settings
# update status line every second
set-option -g status-interval 1
# limit 50 letters in status right
set-option -g status-right-length 50
# status line backgroung color
set-option -g status-bg "#101010"
# status line foreground color
set-option -g status-fg "#f0f0f0"
# status-left format
set-option -g status-left '#{?client_prefix,#[fg=#101010]#[bg=#f0f0f0] #S #[default]#[fg=#f0f0f0]#[default] ,#[bg=#404040] #S #[default]#[fg=#404040]#[default] }'
# status-right format
set-option -g status-right "#[fg=#c0c0c0] %Y/%m/%d (%a) #[fg=#404040]#[default]#[bg=#404040] %H:%M:%S #[default]#[fg=#606060,bg=#404040]#[default]#[bg=#606060] #H "

# window-status format
set-window-option -g window-status-format "#[fg=#101010,bg=#202020]#[default]#[fg=#c0c0c0,bg=#202020] #I  #W #[default]#[fg=#202020]#[default]"
# current window-status format
set-window-option -g window-status-current-format "#[fg=#101010,bg=#404040]#[default]#[bg=#404040] #I  #W #[default]#[fg=#404040]#[default]"
