# If you have the machine specific settings (e.g. PATH),
# you can use ~/.zshenv

############################################
# env
############################################
if [ $SHLVL = 1 ]; then
    # Add local binary path
    export PATH="$HOME/.local/bin:$PATH"
    # Add cargo-binstall tools path
    export PATH="$HOME/.cargo/bin:$PATH"

    # anyenv setup
    eval "$(anyenv init -)"
fi

# Additional machine specific completions
fpath=($fpath $HOME/.local/share/zsh/Completions)

############################################
# plugins
############################################
source "/home/miyake/.local/share/zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
source "/home/miyake/.local/share/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
source "/home/miyake/.local/share/zsh/zsh-completions/zsh-completions.plugin.zsh"
source "/home/miyake/.local/share/zsh/fzf-tab/fzf-tab.plugin.zsh"

############################################
# starship
############################################
eval "$(starship init zsh)"

############################################
# alias
############################################
# vim
alias v='nvim'
alias vimrc="nvim ~/.config/nvim/init.lua"
# ls
alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -a'
alias l='ls -al'
# docker
alias d='docker'
alias dockerrm='docker rm $(docker ps -aq)'
alias dockerps='docker ps -a'
# git
alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gg='git graph'
alias gb='git branch'
alias gc='git checkout'
alias gd='git diff'
function gcm {
    git commit -m "$*"
}
# Rust
alias c='cargo'
# other
alias clear='clear -x'
alias ps='ps auxf'
alias less='bat'
alias mkcd=mkcd
function mkcd(){
    mkdir $1;
    cd $1;
}
function swap() {
    local TMPFILE=tmp.$$
    mv "$1" $TMPFILE
    mv "$2" "$1"
    mv $TMPFILE "$2"
}

############################################
# Completion
############################################
# ディレクトリ名の補完で末尾の / を自動的に付加し、次の補完に備える
setopt auto_param_slash
# ファイル名の展開でディレクトリにマッチした場合 末尾に / を付加
setopt mark_dirs
# 補完候補一覧でファイルの種別を識別マーク表示
setopt list_types
# コマンドラインでも # 以降をコメントと見なす
setopt interactive_comments
# コマンドラインの引数で --prefix=/usr などの = 以降でも補完できる
setopt magic_equal_subst
# 語の途中でもカーソル位置で補完
setopt complete_in_word
# 拡張グロブで補完(~とか^とか。例えばless *.txt~memo.txt ならmemo.txt 以外の *.txt にマッチ)
setopt extended_glob

############################################
# CDR
############################################
if [[ -z "$ZSH_CDR_DIR" ]]; then
    ZSH_CDR_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/zsh-cdr
fi
mkdir -p $ZSH_CDR_DIR
autoload -Uz chpwd_recent_dirs cdr
autoload -U add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-file $ZSH_CDR_DIR/recent-dirs
zstyle ':chpwd:*' recent-dirs-max 1000
zstyle ':chpwd:*' recent-dirs-default yes
function fzf-cdr() {
    target_dir=`cdr -l | sed 's/^[^ ][^ ]*  *//' | fzf`
    target_dir=`echo ${target_dir/\~/$HOME}`
    if [ -n "$target_dir" ]; then
        cd $target_dir
    fi
}
alias cdd='fzf-cdr'

############################################
# fzf-tab configuration
############################################
# 補完キャッシュ
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.cache/zsh
# プロセス補完を見やすく
zstyle ':completion:*:*:*:*:processes' command 'ps -u $USER -o pid,stat,%cpu,%mem,cmd'
# 小文字でも大文字に引っかかるようにする．大文字の場合は大文字だけで補完．
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind='backspace:abort'
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this plugin. See Aloxaf/fzf-tab#455.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

############################################
# History
############################################
HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.zsh_history

setopt hist_expire_dups_first
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_save_no_dups
setopt share_history

function select-history() {
  BUFFER=$(history -n -r 1 | fzf --no-sort +m --query "$LBUFFER" --exact --prompt="History > ")
  CURSOR=$#BUFFER
  zle accept-line
}
zle -N select-history

############################################
# Key-bind
############################################

# Disable zsh flow control (C^q and C^s)
setopt no_flow_control

bindkey '^r' select-history
bindkey '^q' push-input

############################################
# Startup program
############################################
if [ $SHLVL = 1 ]; then
    if [ "$(tmux list-sessions 2> /dev/null )" != "" ]; then
        tmux a > /tmp/tmux-$(whoami)
    else
        tmux > /tmp/tmux-$(whoami)
    fi
fi

if [ -z "$ORCA" ] && [ "$(cat /tmp/tmux-$(whoami))" = "[exited]" ]; then
    exit
fi
